import { getPalette } from "./palettes";
import type { PostDesign, Template, TemplateId } from "./types";

export const TEMPLATES: Template[] = [
  {
    id: "quote",
    name: "Citação",
    description: "Frase serifada com atribuição",
    group: "editorial",
    fontId: "instrument-serif",
    paletteId: "ink",
    image: null,
    overlay: 0,
    headlineSize: 72,
    letterSpacing: -1,
    lineHeight: 1.12,
    align: "left",
    uppercase: false,
    padding: 88,
    copy: {
      kicker: "Ensaio 04",
      headline: "A forma é a substância que se vê.",
      subhead: "Atelier Grafia",
      body: "",
      cta: "grafia",
    },
  },
  {
    id: "announcement",
    name: "Anúncio",
    description: "Lançamento com chamada",
    group: "promo",
    fontId: "syne",
    paletteId: "paper",
    image: null,
    overlay: 0,
    headlineSize: 84,
    letterSpacing: -2,
    lineHeight: 0.98,
    align: "left",
    uppercase: false,
    padding: 80,
    copy: {
      kicker: "Lançamento",
      headline: "Coleção de verão",
      subhead: "Peças limitadas",
      body: "Disponível a partir de 22 de setembro. Envio para todo o Brasil.",
      cta: "Ver coleção",
    },
  },
  {
    id: "product",
    name: "Produto",
    description: "Foto em destaque e preço",
    group: "promo",
    fontId: "figtree",
    paletteId: "paper",
    image: "/textures/linen.jpg",
    overlay: 8,
    headlineSize: 56,
    letterSpacing: -0.5,
    lineHeight: 1.1,
    align: "left",
    uppercase: false,
    padding: 56,
    copy: {
      kicker: "Novo",
      headline: "Óleo de alecrim",
      subhead: "R$ 89",
      body: "Extraído a frio · 30 ml",
      cta: "Encomendar",
    },
  },
  {
    id: "tip",
    name: "Dica",
    description: "Cartão didático numerado",
    group: "editorial",
    fontId: "newsreader",
    paletteId: "olive",
    image: "/textures/botanical.jpg",
    overlay: 46,
    headlineSize: 64,
    letterSpacing: -1,
    lineHeight: 1.15,
    align: "left",
    uppercase: false,
    padding: 72,
    copy: {
      kicker: "Dica 07",
      headline: "Deixe o texto respirar.",
      subhead: "",
      body: "Margens generosas valem mais do que uma fonte extra. O vazio é parte do desenho.",
      cta: "Salvar dica",
    },
  },
  {
    id: "event",
    name: "Evento",
    description: "Data, título e local",
    group: "promo",
    fontId: "oswald",
    paletteId: "navy",
    image: "/textures/window.jpg",
    overlay: 52,
    headlineSize: 78,
    letterSpacing: 0,
    lineHeight: 1.02,
    align: "left",
    uppercase: true,
    padding: 72,
    copy: {
      kicker: "22 SET",
      headline: "Noite de abertura",
      subhead: "Casa Grafia · Pinheiros",
      body: "Das 19h às 22h. Entrada franca com inscrição.",
      cta: "Reservar lugar",
    },
  },
  {
    id: "editorial",
    name: "Editorial",
    description: "Capa de revista",
    group: "editorial",
    fontId: "playfair",
    paletteId: "ink",
    image: "/textures/paper-dark.jpg",
    overlay: 28,
    headlineSize: 96,
    letterSpacing: -2,
    lineHeight: 0.92,
    align: "left",
    uppercase: false,
    padding: 64,
    copy: {
      kicker: "Vol. 12",
      headline: "Tipos vivos",
      subhead: "Uma conversa sobre letra e espaço",
      body: "",
      cta: "Ler ensaio",
    },
  },
  {
    id: "story",
    name: "História",
    description: "Vertical para stories",
    group: "story",
    fontId: "fraunces",
    paletteId: "clay",
    image: "/textures/plaster.jpg",
    overlay: 38,
    headlineSize: 80,
    letterSpacing: -1,
    lineHeight: 1.05,
    align: "center",
    uppercase: false,
    padding: 80,
    copy: {
      kicker: "Bastidores",
      headline: "O ateliê abre as portas",
      subhead: "Uma semana de processos",
      body: "",
      cta: "@grafia.studio",
    },
  },
  {
    id: "minimal",
    name: "Mínima",
    description: "Uma linha, muito ar",
    group: "editorial",
    fontId: "instrument-serif",
    paletteId: "paper",
    image: null,
    overlay: 0,
    headlineSize: 56,
    letterSpacing: 0,
    lineHeight: 1.2,
    align: "center",
    uppercase: false,
    padding: 96,
    copy: {
      kicker: "",
      headline: "Menos ruído. Mais letra.",
      subhead: "",
      body: "",
      cta: "",
    },
  },
  {
    id: "band",
    name: "Faixa",
    description: "Foto com faixa de texto",
    group: "story",
    fontId: "space-grotesk",
    paletteId: "ink",
    image: "/textures/slate.jpg",
    overlay: 12,
    headlineSize: 52,
    letterSpacing: 0.5,
    lineHeight: 1.1,
    align: "left",
    uppercase: true,
    padding: 0,
    copy: {
      kicker: "Campanha",
      headline: "Feito para durar",
      subhead: "Outono 2026",
      body: "",
      cta: "Descobrir",
    },
  },
  {
    id: "split",
    name: "Retrato",
    description: "Metade imagem, metade tipo",
    group: "editorial",
    fontId: "newsreader",
    paletteId: "blush",
    image: "/textures/plaster.jpg",
    overlay: 0,
    headlineSize: 58,
    letterSpacing: -1,
    lineHeight: 1.12,
    align: "left",
    uppercase: false,
    padding: 56,
    copy: {
      kicker: "Perfil",
      headline: "Luz, papel e silêncio.",
      subhead: "Retratos de ateliê",
      body: "Uma série sobre o ofício de imprimir.",
      cta: "Ver série",
    },
  },
  {
    id: "offer",
    name: "Oferta",
    description: "Número grande e condição",
    group: "promo",
    fontId: "bebas",
    paletteId: "forest",
    image: null,
    overlay: 0,
    headlineSize: 180,
    letterSpacing: 0,
    lineHeight: 0.85,
    align: "left",
    uppercase: true,
    padding: 72,
    copy: {
      kicker: "Somente este fim de semana",
      headline: "30%",
      subhead: "em toda a casa",
      body: "Válido até domingo, à meia-noite.",
      cta: "Usar cupom GRAFIA30",
    },
  },
  {
    id: "carousel",
    name: "Carrossel",
    description: "Capa numerada de série",
    group: "story",
    fontId: "syne",
    paletteId: "slate",
    image: "/textures/window.jpg",
    overlay: 50,
    headlineSize: 70,
    letterSpacing: -1.5,
    lineHeight: 1.05,
    align: "left",
    uppercase: false,
    padding: 72,
    copy: {
      kicker: "01 / 06",
      headline: "Como compor um post",
      subhead: "Um guia rápido de ateliê",
      body: "Deslize para o próximo passo.",
      cta: "Deslizar",
    },
  },
];

export function getTemplate(id: TemplateId): Template {
  return TEMPLATES.find((t) => t.id === id) ?? TEMPLATES[0];
}

export function designFromTemplate(
  template: Template,
  formatId: PostDesign["formatId"],
  id?: string,
): PostDesign {
  const palette = getPalette(template.paletteId);
  return {
    id: id ?? crypto.randomUUID(),
    name: template.name,
    templateId: template.id,
    formatId,
    fontId: template.fontId,
    kicker: template.copy.kicker,
    headline: template.copy.headline,
    subhead: template.copy.subhead,
    body: template.copy.body,
    cta: template.copy.cta,
    headlineSize: template.headlineSize,
    letterSpacing: template.letterSpacing,
    lineHeight: template.lineHeight,
    align: template.align,
    uppercase: template.uppercase,
    bgColor: palette.bg,
    textColor: palette.text,
    accentColor: palette.accent,
    overlay: template.overlay,
    padding: template.padding,
    imageSrc: template.image,
    imageFit: "cover",
    imagePos: "center",
    updatedAt: Date.now(),
  };
}
